name: gtuner
description: Mobile Guitar Tuner.

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  pitchupdart: 
    path: ./pitchup_dart
  flutter_audio_capture: ^1.1.0
  pitch_detector_dart: ^0.0.2
  shared_preferences: ^2.0.15
  permission_handler: ^10.0.0
  google_mobile_ads: ^1.3.0
  show_up_animation: ^2.0.0
  numberpicker: ^2.1.1
  google_fonts: ^3.0.1
  just_audio: ^0.9.28

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
