name: gtuner
description: Mobile guitar Tuner.

publish_to: 'none'
version: 1.6.0

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  pitchupdart: 
    path: ./pitchup_dart
  flutter_audio_capture: ^1.1.0
  pitch_detector_dart: ^0.0.2
  shared_preferences: ^2.0.11
  google_mobile_ads: ^0.13.0
  permission_handler: ^8.3.0
  audioplayers: ^0.20.1
  numberpicker: ^2.1.1
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icon.png"
