name: gtuner
description: Mobile Guitar Tuner.

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  pitchupdart: 
    path: ./pitchup_dart
  flutter_audio_capture: ^1.1.4
  pitch_detector_dart: ^0.0.2
  shared_preferences: ^2.1.1
  permission_handler: ^10.2.0
  google_mobile_ads: ^3.0.0
  show_up_animation: ^2.0.0
  numberpicker: ^2.1.2
  google_fonts: ^4.0.4
  just_audio: ^0.9.32

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.19

flutter_icons:
  # flutter pub run flutter_launcher_icons:main

  android: "launcher_icon"
  ios: true
  image_path: "images/Icon.png"
  min_sdk_android: 23
  adaptive_icon_background: "#0b0b0b"

flutter_native_splash:
  # flutter pub run flutter_native_splash:create
  # flutter pub run flutter_native_splash:remove

  color: "#0b0b0b"
  background_color: "#0b0b0b"

  image: images/splash.png

  branding: images/dimo.png
  branding_mode: bottom

  color_dark: "#0b0b0b"

  image_dark:  images/splash.png

  branding_dark: images/dimo.png

  fullscreen: true

  android_12:
    image: images/Android12_splash.png
    icon_background_color: "#0b0b0b"
    image_dark: images/Android12_splash.png
    icon_background_color_dark: "#0b0b0b"
    background_color: "#0b0b0b"
    branding: images/dimo_android12.png

  web: false

flutter:
  uses-material-design: true
  assets:
    - images/
