name: gtuner
description: Mobile guitar Tuner.

publish_to: 'none'
version: 1.1.0

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  pitchupdart: 
    path: ./pitchup_dart
  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_audio_capture: ^1.1.0
  pitch_detector_dart: ^0.0.2
  shared_preferences: ^2.0.11
  permission_handler: ^8.3.0
  adaptive_theme: ^2.3.0
  flutter_fft: ^1.0.2+6
  numberpicker: ^2.1.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icon.png"
